// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgb0a49_7w3v4N9ffa7jJtJfHpAuDBws8',
    appId: '1:631202241463:web:af7ef5ea1b081c4e09e632',
    messagingSenderId: '631202241463',
    projectId: 'app-05-afe8a',
    authDomain: 'app-05-afe8a.firebaseapp.com',
    databaseURL: 'https://app-05-afe8a-default-rtdb.firebaseio.com',
    storageBucket: 'app-05-afe8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATAsWobIpCnmCMDrYFoqGKFU3lr5Nsejk',
    appId: '1:631202241463:android:613698eac69ac74f09e632',
    messagingSenderId: '631202241463',
    projectId: 'app-05-afe8a',
    databaseURL: 'https://app-05-afe8a-default-rtdb.firebaseio.com',
    storageBucket: 'app-05-afe8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwPGkgWNDJyaTtMt11EWMeleoJLMjrns',
    appId: '1:631202241463:ios:8aa6c855cf104e1809e632',
    messagingSenderId: '631202241463',
    projectId: 'app-05-afe8a',
    databaseURL: 'https://app-05-afe8a-default-rtdb.firebaseio.com',
    storageBucket: 'app-05-afe8a.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwPGkgWNDJyaTtMt11EWMeleoJLMjrns',
    appId: '1:631202241463:ios:8aa6c855cf104e1809e632',
    messagingSenderId: '631202241463',
    projectId: 'app-05-afe8a',
    databaseURL: 'https://app-05-afe8a-default-rtdb.firebaseio.com',
    storageBucket: 'app-05-afe8a.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgb0a49_7w3v4N9ffa7jJtJfHpAuDBws8',
    appId: '1:631202241463:web:70bb4504f64e008409e632',
    messagingSenderId: '631202241463',
    projectId: 'app-05-afe8a',
    authDomain: 'app-05-afe8a.firebaseapp.com',
    databaseURL: 'https://app-05-afe8a-default-rtdb.firebaseio.com',
    storageBucket: 'app-05-afe8a.appspot.com',
  );
}
